
port: 8088
name: meaile-user


mysql:
  host: 127.0.0.1
  port: 3307
  dbname: meaile
  username: root
  password: 123456

jwt:
  key: 'shenchangxingogogo'

redis:
  host: 127.0.0.1
  port: 6379
  username: root
  password: 123456
  database: 0

minio:
  end-point: 127.0.0.1:9000
  access-key: s0Hel7tJJhBAxlXVLQ0W
  secret-key: 93qr8lWBPWGF0GGnoW8bRV4I7nBP7KAT59NVacdx
  bucket-name: meaile-server