
port: 8088
name: meaile-user


mysql:
  host: 127.0.0.1
  port: 3307
  dbname: meaile
  username: root
  password: 123456

jwt:
  key: 'shenchangxingogogo'

redis:
  host: 127.0.0.1
  port: 6379
  username: root
  password: 123456
  database: 0

minio:
  end-point: 127.0.0.1:9000
  access-key: s0Hel7tJJhBAxlXVLQ0W
  secret-key: 93qr8lWBPWGF0GGnoW8bRV4I7nBP7KAT59NVacdx
  bucket-name: meaile-server

huawei-obs:
  url-prefix: http://meaile.site/
  end-point: obs.cn-north-4.myhuaweicloud.com
  access-key: HPUAB5ZLL0MAM1KRJOIY
  secret-key: hugVFJCzNzFu4Ygq0b0cyVb1wETfZzTJrLI2cm0Q
  bucket-name: meaile-server
  path: /meaile-server
  expires: 360000

ai:
  deepseek-key: ''